### ISSUE TITLE
how do you convert Mat 32FC1, 32FC3 to QPixmap?

### ISSUE THREAD

**Issue by richipower** [asmaloney/asmOpenCV#3]

**Comment by asmaloney** [comment]
I'm not sure - I've never dealt with floating point image formats, so you would have to add conversions for them.

I guess `32FC1` would be converted to `QImage::Format_Grayscale8` or `QImage::Format_Grayscale16` (Qt 5.13).

Maybe `32FC3` could be converted to `QImage::Format_RGBA64` (Qt 5.12)?

Once you've added the conversions you can use `ASM::cvMatToQPixmap()` to get a QPixmap.

**Comment by linlin-commit** [comment]
Has it been resolved?I'm also having the same issue

**Comment by asmaloney** [comment]
It depends what you mean by "resolved" 😄  I closed the issue because I answered the question and there was no response (after 2 years).

I didn't add this capability (I've still never worked with floating point image formats) and the poster did not submit a PR for it, so it's not in the code.

I'd be happy to look at a PR for it though!
